version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - celery-worker
      - celery-beat
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker --loglevel=info
    depends_on:
      - redis
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config beat --loglevel=info
    depends_on:
      - redis
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django
