version: '3'
services:
  django:
    container_name: currency_django
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - celery-worker
      - celery-beat
      - db
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate"
  db:
    image: mysql:latest
    container_name: currency_mysql
    environment:
      - MYSQL_DATABASE=currency
      - MYSQL_PASSWORD=11111111
      - MYSQL_ROOT_PASSWORD=11111111
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
  redis:
    container_name: currency_redis
    image: redis:latest
    ports:
      - '6379:6379'
  celery-worker:
    container_name: currency_celery
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker -l info
    depends_on:
      - redis
  celery-beat:
    container_name: currency_beat
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config beat -l info
    depends_on:
      - redis
  nginx:
    container_name: currency_nginx
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django
volumes:
  mysql_data: