# Generated by Django 4.1.5 on 2023-01-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
