# Generated by Django 4.1.5 on 2023-01-09 18:09

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_region_name_alter_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to=news.models.ad_image_rename)),
                ('is_active', models.BooleanField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ad',
                'verbose_name_plural': 'ads',
            },
        ),
    ]
