# Generated by Django 4.1.5 on 2023-01-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_ads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'Ad', 'verbose_name_plural': 'Ads'},
        ),
    ]
