# Generated by Django 4.1.5 on 2023-05-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='date',
            new_name='daily',
        ),
    ]
