# Generated by Django 4.1.5 on 2023-05-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bank',
            name='image',
            field=models.ImageField(null=True, upload_to='images/bank/'),
        ),
    ]
